//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int Id { get; set; }
        public string type { get; set; }
        public string summary { get; set; }
        public string description { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
        public string employee_name { get; set; }
        public string emp_field { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string status { get; set; }
    }
}
