//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class field
    {
        public int Id { get; set; }
        public string field_name { get; set; }
    }
}
