//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class user
    {
        public int Id { get; set; }

        [DisplayName("User Name")]
        public string user_name { get; set; }
        [DisplayName("Email")]
        public string email_id { get; set; }
        [DisplayName("Password")]
        public string password { get; set; }
        [DisplayName("Role")]
        public string role { get; set; }
    }



    public enum Roles
    {
        admin=1,
        manager=2
    }
}
